### ISSUE TITLE
Support PythonCall.jl?

### ISSUE THREAD

**Issue by mohdibntarek** [rejuvyesh/PyCallChainRules.jl#11]
Thanks for this fantastic package. Would it be too much work to generalise the approach here to work with [PythonCall.jl](https://discourse.julialang.org/t/ann-pythoncall-and-juliacall/76778)?

**Comment by rejuvyesh** [comment]
Absolutely! As you can see there is even a PR. Once I merge the DLPack integration I'll get to PythonCall version. Although I'm not sure whether that should be in a different package, say PythonCallChainRules.jl because the interactions and transformations of PyObject is somewhat different than Py.

**Comment by mohdibntarek** [comment]
Sounds great. I think a different package might make more sense.

**Comment by rejuvyesh** [comment]
Should have it soon @ https://github.com/rejuvyesh/PythonCallChainRules.jl
